# Generated by Django 4.0.4 on 2022-05-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
